version: "3"
services:
  sonarqube:
    image: sonarqube:community
    command: -Dsonar.ce.javaOpts=-Xmx1024m
    restart: unless-stopped
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      sonarqube_db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /opt/docker-volume/sonarqube_conf:/opt/sonarqube/conf
      - /opt/docker-volume/sonarqube_data:/opt/sonarqube/data
      - /opt/docker-volume/sonarqube_extensions:/opt/sonarqube/extensions
      - /opt/docker-volume/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - /opt/docker-volume/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - sonar-net  
  sonarqube_db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: postgresql
    container_name: postgresql
    networks:
      - sonar-net 
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - /opt/docker-volume/postgresql:/var/lib/postgresql
      - /opt/docker-volume/postgresql_data:/var/lib/postgresql/data
networks:
  sonar-net:
    external: false
    
volumes:
  /opt/docker-volume/sonarqube_conf:
  /opt/docker-volume/sonarqube_data:
  /opt/docker-volume/sonarqube_extensions:
  /opt/docker-volume/sonarqube_bundled-plugins:
  /opt/docker-volume/postgresql:
  /opt/docker-volume/postgresql_data:
